import jsPDF from 'jspdf';

export interface ReportData {
  restaurant_name: string;
  period: string; // e.g. "March 2026" or "Week of Mar 29, 2026"
  metrics: {
    total_customers: number;
    new_customers: number;
    response_rate: number;
    active_leads: number;
    corp_accounts: number;
    dead_hours_filled: number;
    upcoming_birthdays: number;
  };
  revenue: {
    total: number;
    repeat_visits: number;
    catering: number;
    corporate_recurring: number;
    dead_hours: number;
    birthdays: number;
    delivery_uplift: number;
  };
  top_customers: Array<{ name: string; visits: number; spend: number }>;
  review_summary: {
    total: number;
    avg_rating: number;
    positive_pct: number;
    negative_pct: number;
  };
  ai_digest?: string;
  recommendations?: string;
}

const COLORS = {
  red: [225, 29, 72] as [number, number, number],       // #E11D48
  dark: [24, 24, 27] as [number, number, number],       // zinc-900
  card: [39, 39, 42] as [number, number, number],       // zinc-800
  muted: [113, 113, 122] as [number, number, number],   // zinc-500
  white: [255, 255, 255] as [number, number, number],
  lightGray: [161, 161, 170] as [number, number, number], // zinc-400
  emerald: [16, 185, 129] as [number, number, number],
  purple: [168, 85, 247] as [number, number, number],
  blue: [59, 130, 246] as [number, number, number],
  pink: [236, 72, 153] as [number, number, number],
  amber: [245, 158, 11] as [number, number, number],
};

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount);
}

function drawFooter(doc: jsPDF) {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.muted);
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(`Confidential — Generated by SeatSignals on ${dateStr}`, pageW / 2, pageH - 10, { align: 'center' });
}

export function generateReportPDF(data: ReportData): jsPDF {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentW = pageW - margin * 2;

  // ===== PAGE 1: Executive Summary =====

  // Header bar
  doc.setFillColor(...COLORS.dark);
  doc.rect(0, 0, pageW, 38, 'F');

  // Logo text
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.red);
  doc.text('SeatSignals', margin, 18);

  // Restaurant name
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.white);
  doc.text(data.restaurant_name, margin, 28);

  // Period badge on the right
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.lightGray);
  doc.text(data.period, pageW - margin, 18, { align: 'right' });
  doc.setFontSize(8);
  doc.text('Performance Report', pageW - margin, 25, { align: 'right' });

  // Divider
  let y = 44;
  doc.setDrawColor(...COLORS.red);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageW - margin, y);

  // Total Revenue - big callout
  y += 10;
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.muted);
  doc.setFont('helvetica', 'normal');
  doc.text('TOTAL ATTRIBUTED REVENUE', margin, y);

  y += 10;
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.red);
  doc.text(formatCurrency(data.revenue.total), margin, y);

  // === Key Metrics Grid (3x2) ===
  y += 14;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text('KEY METRICS', margin, y);

  y += 6;
  const metricItems = [
    { label: 'Total Customers', value: data.metrics.total_customers.toLocaleString() },
    { label: 'New Customers', value: data.metrics.new_customers.toLocaleString() },
    { label: 'Review Response Rate', value: `${data.metrics.response_rate}%` },
    { label: 'Active Leads', value: data.metrics.active_leads.toLocaleString() },
    { label: 'Corp Accounts', value: data.metrics.corp_accounts.toLocaleString() },
    { label: 'Dead Hours Filled', value: data.metrics.dead_hours_filled.toLocaleString() },
  ];

  const cols = 3;
  const cellW = contentW / cols;
  const cellH = 22;

  metricItems.forEach((item, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const cx = margin + col * cellW;
    const cy = y + row * cellH;

    // Card background
    doc.setFillColor(245, 245, 248);
    doc.roundedRect(cx + 1, cy, cellW - 3, cellH - 3, 2, 2, 'F');

    // Label
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.muted);
    doc.text(item.label, cx + 5, cy + 8);

    // Value
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    doc.text(item.value, cx + 5, cy + 17);
  });

  y += Math.ceil(metricItems.length / cols) * cellH + 8;

  // === Revenue Breakdown - horizontal bar chart ===
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text('REVENUE BREAKDOWN', margin, y);

  y += 6;
  const revenueItems = [
    { label: 'Repeat Visits', value: data.revenue.repeat_visits, color: COLORS.emerald },
    { label: 'Catering', value: data.revenue.catering, color: COLORS.purple },
    { label: 'Corporate Recurring', value: data.revenue.corporate_recurring, color: COLORS.blue },
    { label: 'Dead Hours', value: data.revenue.dead_hours, color: COLORS.red },
    { label: 'Birthdays', value: data.revenue.birthdays, color: COLORS.pink },
    { label: 'Delivery Uplift', value: data.revenue.delivery_uplift, color: COLORS.amber },
  ];

  const maxRev = Math.max(...revenueItems.map(r => r.value), 1);
  const barMaxW = contentW - 70; // leave room for labels + values
  const barH = 6;
  const barSpacing = 14;

  revenueItems.forEach((item, i) => {
    const cy = y + i * barSpacing;

    // Label
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.muted);
    doc.text(item.label, margin, cy + 4);

    // Bar background
    const barX = margin + 42;
    doc.setFillColor(230, 230, 235);
    doc.roundedRect(barX, cy, barMaxW, barH, 1, 1, 'F');

    // Bar fill
    const barW = Math.max((item.value / maxRev) * barMaxW, 1);
    doc.setFillColor(...item.color);
    doc.roundedRect(barX, cy, barW, barH, 1, 1, 'F');

    // Value
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    doc.text(formatCurrency(item.value), barX + barMaxW + 3, cy + 4.5);
  });

  drawFooter(doc);

  // ===== PAGE 2: Details =====
  doc.addPage();

  // Header
  doc.setFillColor(...COLORS.dark);
  doc.rect(0, 0, pageW, 20, 'F');
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.red);
  doc.text('SeatSignals', margin, 13);
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.lightGray);
  doc.text(`${data.restaurant_name}  |  ${data.period}`, pageW - margin, 13, { align: 'right' });

  y = 30;

  // === Top Customers Table ===
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text('TOP CUSTOMERS BY SPEND', margin, y);

  y += 6;
  const colWidths = [8, 60, 30, 40]; // rank, name, visits, spend
  const tableX = margin;

  // Table header
  doc.setFillColor(...COLORS.dark);
  doc.rect(tableX, y, contentW, 8, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  doc.text('#', tableX + 3, y + 5.5);
  doc.text('Customer', tableX + colWidths[0] + 4, y + 5.5);
  doc.text('Visits', tableX + colWidths[0] + colWidths[1] + 4, y + 5.5);
  doc.text('Total Spend', tableX + colWidths[0] + colWidths[1] + colWidths[2] + 4, y + 5.5);

  y += 8;

  data.top_customers.slice(0, 10).forEach((cust, i) => {
    const rowY = y + i * 7;
    // Alternate row color
    if (i % 2 === 0) {
      doc.setFillColor(248, 248, 250);
      doc.rect(tableX, rowY, contentW, 7, 'F');
    }

    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.dark);
    doc.text(`${i + 1}`, tableX + 3, rowY + 5);
    doc.text(cust.name.length > 28 ? cust.name.substring(0, 28) + '...' : cust.name, tableX + colWidths[0] + 4, rowY + 5);
    doc.text(`${cust.visits}`, tableX + colWidths[0] + colWidths[1] + 4, rowY + 5);
    doc.setFont('helvetica', 'bold');
    doc.text(formatCurrency(cust.spend), tableX + colWidths[0] + colWidths[1] + colWidths[2] + 4, rowY + 5);
  });

  y += data.top_customers.slice(0, 10).length * 7 + 10;

  // === Review Performance ===
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text('REVIEW PERFORMANCE', margin, y);

  y += 6;
  const reviewStats = [
    { label: 'Total Reviews', value: data.review_summary.total.toLocaleString() },
    { label: 'Avg Rating', value: `${data.review_summary.avg_rating.toFixed(1)} / 5.0` },
    { label: 'Positive', value: `${data.review_summary.positive_pct}%` },
    { label: 'Negative', value: `${data.review_summary.negative_pct}%` },
  ];

  const reviewCellW = contentW / 4;
  reviewStats.forEach((stat, i) => {
    const cx = margin + i * reviewCellW;
    doc.setFillColor(245, 245, 248);
    doc.roundedRect(cx + 1, y, reviewCellW - 3, 18, 2, 2, 'F');

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.muted);
    doc.text(stat.label, cx + 5, y + 7);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    doc.text(stat.value, cx + 5, y + 15);
  });

  y += 26;

  // === Rating bar visualization ===
  doc.setFillColor(230, 230, 235);
  doc.roundedRect(margin, y, contentW, 6, 1, 1, 'F');
  const posW = (data.review_summary.positive_pct / 100) * contentW;
  if (posW > 0) {
    doc.setFillColor(...COLORS.emerald);
    doc.roundedRect(margin, y, posW, 6, 1, 1, 'F');
  }
  const negW = (data.review_summary.negative_pct / 100) * contentW;
  if (negW > 0) {
    doc.setFillColor(...COLORS.red);
    doc.roundedRect(margin + contentW - negW, y, negW, 6, 1, 1, 'F');
  }

  y += 10;
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.emerald);
  doc.text(`Positive ${data.review_summary.positive_pct}%`, margin, y);
  doc.setTextColor(...COLORS.muted);
  const neutralPct = 100 - data.review_summary.positive_pct - data.review_summary.negative_pct;
  doc.text(`Neutral ${neutralPct}%`, margin + contentW / 2 - 10, y);
  doc.setTextColor(...COLORS.red);
  doc.text(`Negative ${data.review_summary.negative_pct}%`, pageW - margin, y, { align: 'right' });

  y += 12;

  // === AI Digest ===
  if (data.ai_digest) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    doc.text('AI INSIGHTS', margin, y);

    y += 5;
    doc.setFillColor(245, 245, 248);
    const digestLines = doc.splitTextToSize(data.ai_digest, contentW - 10);
    const digestH = digestLines.length * 4.5 + 8;
    doc.roundedRect(margin, y, contentW, digestH, 2, 2, 'F');

    // Red accent bar
    doc.setFillColor(...COLORS.red);
    doc.rect(margin, y, 2, digestH, 'F');

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.dark);
    doc.text(digestLines, margin + 8, y + 6);

    y += digestH + 8;
  }

  // === Recommendations ===
  if (data.recommendations) {
    // Check if we need a new page
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    doc.text('RECOMMENDATIONS', margin, y);

    y += 5;
    const recLines = data.recommendations.split('\n').filter(l => l.trim());
    recLines.forEach((line) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      const wrapped = doc.splitTextToSize(line.trim(), contentW - 12);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.dark);

      // Bullet point
      doc.setFillColor(...COLORS.red);
      doc.circle(margin + 2.5, y + 1, 1, 'F');
      doc.text(wrapped, margin + 7, y + 2.5);

      y += wrapped.length * 4.5 + 4;
    });
  }

  drawFooter(doc);

  return doc;
}
