import { jsPDF } from 'jspdf';

export interface InvoiceLineItem {
  description: string;
  quantity: number;
  unit_price: number;
}

export interface InvoiceData {
  restaurant_name: string;
  restaurant_address: string;
  logo_url?: string;
  client_name: string;
  client_company?: string;
  client_address?: string;
  invoice_number: string;
  date: string;
  due_date: string;
  line_items: InvoiceLineItem[];
  tax_rate: number;
  notes?: string;
  payment_terms?: string;
}

const ACCENT = '#E11D48';
const DARK = '#111111';
const GRAY = '#666666';
const LIGHT_GRAY = '#999999';
const LINE_GRAY = '#DDDDDD';

function drawFooter(doc: jsPDF, restaurantName: string) {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  doc.setDrawColor(LINE_GRAY);
  doc.line(20, pageH - 20, pageW - 20, pageH - 20);
  doc.setFontSize(8);
  doc.setTextColor(LIGHT_GRAY);
  doc.text(restaurantName, 20, pageH - 13);
  doc.text('Generated by SeatSignals', pageW - 20, pageH - 13, { align: 'right' });
}

export function generateInvoicePDF(data: InvoiceData): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const rightCol = pageW - margin;

  // ── Header: Restaurant info + INVOICE badge ──

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(DARK);
  doc.text(data.restaurant_name, margin, 30);

  if (data.restaurant_address) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(GRAY);
    const addrLines = doc.splitTextToSize(data.restaurant_address, 90);
    doc.text(addrLines, margin, 38);
  }

  // INVOICE label on the right
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(ACCENT);
  doc.text('INVOICE', rightCol, 30, { align: 'right' });

  // Accent line
  doc.setDrawColor(ACCENT);
  doc.setLineWidth(0.8);
  let y = 50;
  doc.line(margin, y, rightCol, y);

  // ── Invoice details + Client info ──

  y = 62;
  const leftDetail = margin;
  const rightDetail = pageW / 2 + 10;

  // Invoice details (right side)
  const detailLabel = (label: string, value: string, xBase: number, yPos: number) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(ACCENT);
    doc.text(label, xBase, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(DARK);
    doc.text(value, xBase + 35, yPos);
  };

  detailLabel('Invoice #:', data.invoice_number, rightDetail, y);
  detailLabel('Date:', data.date, rightDetail, y + 7);
  detailLabel('Due Date:', data.due_date, rightDetail, y + 14);

  // Client info (left side)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(ACCENT);
  doc.text('BILL TO:', leftDetail, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(DARK);
  let clientY = y + 7;
  doc.text(data.client_name, leftDetail, clientY);
  clientY += 5;

  if (data.client_company) {
    doc.setTextColor(GRAY);
    doc.text(data.client_company, leftDetail, clientY);
    clientY += 5;
  }

  if (data.client_address) {
    doc.setTextColor(GRAY);
    doc.setFontSize(9);
    const clientAddrLines = doc.splitTextToSize(data.client_address, 80);
    doc.text(clientAddrLines, leftDetail, clientY);
  }

  // ── Line Items Table ──

  y = 100;

  // Table header background
  doc.setFillColor(225, 29, 72); // ACCENT as RGB
  doc.rect(margin, y, rightCol - margin, 8, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor('#FFFFFF');

  const colDesc = margin + 3;
  const colQty = margin + 95;
  const colUnit = margin + 120;
  const colTotal = rightCol - 3;

  doc.text('Description', colDesc, y + 5.5);
  doc.text('Qty', colQty, y + 5.5);
  doc.text('Unit Price', colUnit, y + 5.5);
  doc.text('Total', colTotal, y + 5.5, { align: 'right' });

  y += 8;

  // Table rows
  let subtotal = 0;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);

  for (let i = 0; i < data.line_items.length; i++) {
    const item = data.line_items[i];
    const lineTotal = item.quantity * item.unit_price;
    subtotal += lineTotal;

    // Alternate row shading
    if (i % 2 === 0) {
      doc.setFillColor(248, 248, 250);
      doc.rect(margin, y, rightCol - margin, 8, 'F');
    }

    doc.setTextColor(DARK);

    // Wrap description if long
    const descLines = doc.splitTextToSize(item.description, 85);
    const rowH = Math.max(8, descLines.length * 4.5 + 3);

    doc.text(descLines, colDesc, y + 5.5);
    doc.text(String(item.quantity), colQty, y + 5.5);
    doc.text(`$${item.unit_price.toFixed(2)}`, colUnit, y + 5.5);
    doc.text(`$${lineTotal.toFixed(2)}`, colTotal, y + 5.5, { align: 'right' });

    y += rowH;

    // Light separator
    doc.setDrawColor(LINE_GRAY);
    doc.setLineWidth(0.1);
    doc.line(margin, y, rightCol, y);
  }

  // ── Totals ──

  y += 8;
  const labelX = rightCol - 60;
  const valueX = rightCol;

  const totalRow = (label: string, value: string, bold = false, accent = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(bold ? 11 : 10);
    doc.setTextColor(accent ? ACCENT : DARK);
    doc.text(label, labelX, y);
    doc.text(value, valueX, y, { align: 'right' });
    y += 7;
  };

  totalRow('Subtotal', `$${subtotal.toFixed(2)}`);

  const taxAmount = subtotal * (data.tax_rate / 100);
  totalRow(`Tax (${data.tax_rate}%)`, `$${taxAmount.toFixed(2)}`);

  const grandTotal = subtotal + taxAmount;

  // Bold total line
  doc.setDrawColor(ACCENT);
  doc.setLineWidth(0.5);
  doc.line(labelX, y - 2, valueX, y - 2);
  y += 3;

  totalRow('Total Due', `$${grandTotal.toFixed(2)}`, true, true);

  // ── Payment Terms ──

  if (data.payment_terms) {
    y += 6;
    doc.setDrawColor(LINE_GRAY);
    doc.setLineWidth(0.3);
    doc.line(margin, y, rightCol, y);
    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(ACCENT);
    doc.text('Payment Terms', margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(DARK);
    const termLines = doc.splitTextToSize(data.payment_terms, pageW - 40);
    doc.text(termLines, margin, y);
    y += termLines.length * 4.5 + 4;
  }

  // ── Notes ──

  if (data.notes) {
    y += 4;
    doc.setDrawColor(LINE_GRAY);
    doc.setLineWidth(0.3);
    doc.line(margin, y, rightCol, y);
    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(ACCENT);
    doc.text('Notes', margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(DARK);
    const noteLines = doc.splitTextToSize(data.notes, pageW - 40);
    doc.text(noteLines, margin, y);
  }

  drawFooter(doc, data.restaurant_name);

  return doc;
}
