import { jsPDF } from 'jspdf';

export interface ProposalData {
  restaurant_name: string;
  restaurant_address: string;
  logo_url?: string;
  company_name: string;
  contact_name: string;
  contact_email: string;
  event_date?: string;
  headcount?: number;
  menu_items: Array<{
    name: string;
    description?: string;
    price_per_person: number;
    min_order?: number;
  }>;
  notes?: string;
  delivery_fee?: number;
  tax_rate?: number;
}

const ACCENT = '#E11D48';
const DARK = '#111111';
const GRAY = '#666666';
const LIGHT_GRAY = '#999999';
const LINE_GRAY = '#DDDDDD';

function drawFooter(doc: jsPDF, address: string) {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  doc.setDrawColor(LINE_GRAY);
  doc.line(20, pageH - 20, pageW - 20, pageH - 20);
  doc.setFontSize(8);
  doc.setTextColor(LIGHT_GRAY);
  doc.text(address, 20, pageH - 13);
  doc.text('Generated by SeatSignals', pageW - 20, pageH - 13, { align: 'right' });
}

export function generateProposalPDF(data: ProposalData): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // ── Page 1: Cover ──

  // Restaurant name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(DARK);
  doc.text(data.restaurant_name, 20, 50);

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(18);
  doc.setTextColor(GRAY);
  doc.text('Catering Proposal', 20, 62);

  // Accent line
  doc.setDrawColor(ACCENT);
  doc.setLineWidth(0.8);
  doc.line(20, 70, pageW - 20, 70);

  // Details
  let y = 85;
  const lineHeight = 9;

  const detail = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(ACCENT);
    doc.text(label, 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(DARK);
    doc.text(value, 75, y);
    y += lineHeight;
  };

  detail('Prepared for:', data.company_name);
  detail('Contact:', `${data.contact_name} (${data.contact_email})`);
  detail('Date:', today);
  if (data.event_date) {
    detail('Event Date:', data.event_date);
  }
  if (data.headcount) {
    detail('Headcount:', `${data.headcount} guests`);
  }

  drawFooter(doc, data.restaurant_address);

  // ── Page 2: Menu & Pricing ──

  doc.addPage();
  y = 30;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(ACCENT);
  doc.text('Menu Selection', 20, y);
  y += 12;

  // Table header
  const colItem = 20;
  const colDesc = 80;
  const colPrice = pageW - 20;

  doc.setDrawColor(ACCENT);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageW - 20, y);
  y += 6;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(DARK);
  doc.text('Item', colItem, y);
  doc.text('Description', colDesc, y);
  doc.text('Price/Person', colPrice, y, { align: 'right' });
  y += 4;
  doc.setDrawColor(LINE_GRAY);
  doc.setLineWidth(0.3);
  doc.line(20, y, pageW - 20, y);
  y += 6;

  // Menu items
  let subtotal = 0;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  for (const item of data.menu_items) {
    const itemTotal = item.price_per_person * (data.headcount || 1);
    subtotal += itemTotal;

    doc.setTextColor(DARK);
    doc.setFont('helvetica', 'normal');
    doc.text(item.name, colItem, y);

    // Wrap description if it exists
    if (item.description) {
      doc.setTextColor(GRAY);
      const descLines = doc.splitTextToSize(item.description, colPrice - colDesc - 30);
      doc.text(descLines, colDesc, y);
    }

    doc.setTextColor(DARK);
    doc.text(`$${item.price_per_person.toFixed(2)}`, colPrice, y, { align: 'right' });

    const descHeight = item.description
      ? doc.splitTextToSize(item.description, colPrice - colDesc - 30).length * 5
      : 0;
    y += Math.max(7, descHeight + 2);

    // Light separator
    doc.setDrawColor(LINE_GRAY);
    doc.setLineWidth(0.1);
    doc.line(20, y, pageW - 20, y);
    y += 5;
  }

  // Totals section
  y += 4;
  const labelX = pageW - 70;
  const valueX = pageW - 20;

  const totalRow = (label: string, value: number, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(bold ? 11 : 10);
    doc.setTextColor(bold ? ACCENT : DARK);
    doc.text(label, labelX, y);
    doc.text(`$${value.toFixed(2)}`, valueX, y, { align: 'right' });
    y += 7;
  };

  totalRow('Subtotal', subtotal);

  if (data.delivery_fee) {
    totalRow('Delivery Fee', data.delivery_fee);
    subtotal += data.delivery_fee;
  }

  let tax = 0;
  if (data.tax_rate) {
    tax = subtotal * (data.tax_rate / 100);
    totalRow(`Tax (${data.tax_rate}%)`, tax);
    subtotal += tax;
  }

  // Bold total line
  doc.setDrawColor(ACCENT);
  doc.setLineWidth(0.5);
  doc.line(labelX, y - 2, valueX, y - 2);
  y += 3;
  totalRow('Total', subtotal, true);

  // Notes section
  if (data.notes) {
    y += 8;
    doc.setDrawColor(LINE_GRAY);
    doc.setLineWidth(0.3);
    doc.line(20, y, pageW - 20, y);
    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(ACCENT);
    doc.text('Notes', 20, y);
    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(DARK);
    const noteLines = doc.splitTextToSize(data.notes, pageW - 40);
    doc.text(noteLines, 20, y);
  }

  drawFooter(doc, data.restaurant_address);

  return doc;
}
