ALTER TABLE customers ADD COLUMN IF NOT EXISTS company TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS job_title TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS linkedin_url TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS instagram_handle TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS twitter_handle TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS enrichment_data JSONB;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS enriched_at TIMESTAMPTZ;
